import { avalon, platform, isObject, modern } from '../seed/core'
import { $$skipArray } from './reserved'
// import { Mutation } from './Mutation'
// import { Computed } from './Computed'
// import { IProxy, canHijack, createProxy } from './share'